### ISSUE TITLE
Incorrect result in integration with Apache Superset

### ISSUE THREAD

**Issue by E-Babkin** [OpenLinkSoftware/Virtuoso-SQLAlchemy#2]
When Virtuoso SQLAlchemy dialect was plugged into Apache Superset and filter conditions are set inside Superset for an Virtuoso-based dataset, application of the filter results in the error "name 'IRI_ID_Literal' is not defined":
![image](https://github.com/OpenLinkSoftware/Virtuoso-SQLAlchemy/assets/9838609/5b13262c-8361-43cd-b590-18da62cad625)

That error occurs in all cases:
1) a filter is set inside a dataset or a chart
2) a filter is set in a dashboard

 The same error happens for all variants of the access to Virtuoso:
 1) native relational table
 2) saved SQL query
 3) saved SPARQL query.

**Comment by E-Babkin** [comment]
A complete trace from Superset follows:

name 'IRI_ID_Literal' is not defined
2024-01-28 12:03:39 Traceback (most recent call last):
2024-01-28 12:03:39   File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1823, in full_dispatch_request
2024-01-28 12:03:39     rv = self.dispatch_request()
2024-01-28 12:03:39   File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1799, in dispatch_request
2024-01-28 12:03:39     return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
2024-01-28 12:03:39   File "/usr/local/lib/python3.9/site-packages/flask_appbuilder/security/decorators.py", line 95, in wraps
2024-01-28 12:03:39     return f(self, *args, **kwargs)
2024-01-28 12:03:39   File "/app/superset/views/base_api.py", line 127, in wraps
2024-01-28 12:03:39     raise ex
2024-01-28 12:03:39   File "/app/superset/views/base_api.py", line 121, in wraps
2024-01-28 12:03:39     duration, response = time_function(f, self, *args, **kwargs)
2024-01-28 12:03:39   File "/app/superset/utils/core.py", line 1526, in time_function
2024-01-28 12:03:39     response = func(*args, **kwargs)
2024-01-28 12:03:39   File "/app/superset/utils/log.py", line 255, in wrapper
2024-01-28 12:03:39     value = f(*args, **kwargs)
2024-01-28 12:03:39   File "/app/superset/charts/data/api.py", line 256, in data
2024-01-28 12:03:39     return self._get_data_response(
2024-01-28 12:03:39   File "/app/superset/charts/data/api.py", line 415, in _get_data_response
2024-01-28 12:03:39     result = command.run(force_cached=force_cached)
2024-01-28 12:03:39   File "/app/superset/charts/data/commands/get_data_command.py", line 45, in run
2024-01-28 12:03:39     payload = self._query_context.get_payload(
2024-01-28 12:03:39   File "/app/superset/common/query_context.py", line 100, in get_payload
2024-01-28 12:03:39     return self._processor.get_payload(cache_query_context, force_cached)
2024-01-28 12:03:39   File "/app/superset/common/query_context_processor.py", line 590, in get_payload
2024-01-28 12:03:39     query_results = [
2024-01-28 12:03:39   File "/app/superset/common/query_context_processor.py", line 591, in <listcomp>
2024-01-28 12:03:39     get_query_results(
2024-01-28 12:03:39   File "/app/superset/common/query_actions.py", line 225, in get_query_results
2024-01-28 12:03:39     return result_func(query_context, query_obj, force_cached)
2024-01-28 12:03:39   File "/app/superset/common/query_actions.py", line 103, in _get_full
2024-01-28 12:03:39     payload = query_context.get_df_payload(query_obj, force_cached=force_cached)
2024-01-28 12:03:39   File "/app/superset/common/query_context.py", line 121, in get_df_payload
2024-01-28 12:03:39     return self._processor.get_df_payload(
2024-01-28 12:03:39   File "/app/superset/common/query_context_processor.py", line 159, in get_df_payload
2024-01-28 12:03:39     query_result = self.get_query_result(query_obj)
2024-01-28 12:03:39   File "/app/superset/common/query_context_processor.py", line 237, in get_query_result
2024-01-28 12:03:39     result = query_context.datasource.query(query_object.to_dict())
2024-01-28 12:03:39   File "/app/superset/connectors/sqla/models.py", line 1180, in query
2024-01-28 12:03:39     query_str_ext = self.get_query_str_extended(query_obj)
2024-01-28 12:03:39   File "/app/superset/connectors/sqla/models.py", line 843, in get_query_str_extended
2024-01-28 12:03:39     sql = self.database.compile_sqla_query(sqlaq.sqla_query)
2024-01-28 12:03:39   File "/app/superset/models/core.py", line 629, in compile_sqla_query
2024-01-28 12:03:39     sql = str(qry.compile(engine, compile_kwargs={"literal_binds": True}))
2024-01-28 12:03:39   File "/usr/local/lib/python3.9/site-packages/sqlalchemy/sql/elements.py", line 494, in compile
2024-01-28 12:03:39     return self._compiler(dialect, **kw)
2024-01-28 12:03:39   File "/usr/local/lib/python3.9/site-packages/sqlalchemy/sql/elements.py", line 558, in _compiler
2024-01-28 12:03:39     return dialect.statement_compiler(dialect, self, **kw)
2024-01-28 12:03:39   File "/usr/local/lib/python3.9/site-packages/sqlalchemy/sql/compiler.py", line 776, in __init__
2024-01-28 12:03:39     Compiled.__init__(self, dialect, statement, **kwargs)
2024-01-28 12:03:39   File "/usr/local/lib/python3.9/site-packages/sqlalchemy/sql/compiler.py", line 451, in __init__
2024-01-28 12:03:39     self.string = self.process(self.statement, **compile_kwargs)
2024-01-28 12:03:39   File "/usr/local/lib/python3.9/site-packages/sqlalchemy/sql/compiler.py", line 486, in process
2024-01-28 12:03:39     return obj._compiler_dispatch(self, **kwargs)
2024-01-28 12:03:39   File "/usr/local/lib/python3.9/site-packages/sqlalchemy/sql/visitors.py", line 82, in _compiler_dispatch
2024-01-28 12:03:39     return meth(self, **kw)
2024-01-28 12:03:39   File "/usr/local/lib/python3.9/site-packages/sqlalchemy/sql/compiler.py", line 3405, in visit_select
2024-01-28 12:03:39     text = self._compose_select_body(
2024-01-28 12:03:39   File "/usr/local/lib/python3.9/site-packages/sqlalchemy/sql/compiler.py", line 3563, in _compose_select_body
2024-01-28 12:03:39     t = self._generate_delimited_and_list(
2024-01-28 12:03:39   File "/usr/local/lib/python3.9/site-packages/sqlalchemy/sql/compiler.py", line 1702, in _generate_delimited_and_list
2024-01-28 12:03:39     return clauses[0]._compiler_dispatch(self, **kw)
2024-01-28 12:03:39   File "/usr/local/lib/python3.9/site-packages/sqlalchemy/sql/visitors.py", line 82, in _compiler_dispatch
2024-01-28 12:03:39     return meth(self, **kw)
2024-01-28 12:03:39   File "/usr/local/lib/python3.9/site-packages/virtuoso/alchemy.py", line 212, in visit_binary
2024-01-28 12:03:39     return super(VirtuosoSQLCompiler, self).visit_binary(binary, **kwargs)
2024-01-28 12:03:39   File "/usr/local/lib/python3.9/site-packages/sqlalchemy/sql/compiler.py", line 2192, in visit_binary
2024-01-28 12:03:39     return disp(binary, operator_, **kw)
2024-01-28 12:03:39   File "/usr/local/lib/python3.9/site-packages/virtuoso/alchemy.py", line 202, in visit_in_op_binary
2024-01-28 12:03:39     return self._generate_generic_binary(binary, " IN ", **kw)
2024-01-28 12:03:39   File "/usr/local/lib/python3.9/site-packages/sqlalchemy/sql/compiler.py", line 2258, in _generate_generic_binary
2024-01-28 12:03:39     + binary.right._compiler_dispatch(
2024-01-28 12:03:39   File "/usr/local/lib/python3.9/site-packages/sqlalchemy/sql/visitors.py", line 82, in _compiler_dispatch
2024-01-28 12:03:39     return meth(self, **kw)
2024-01-28 12:03:39   File "/usr/local/lib/python3.9/site-packages/sqlalchemy/sql/compiler.py", line 2438, in visit_bindparam
2024-01-28 12:03:39     ret = self.render_literal_bindparam(
2024-01-28 12:03:39   File "/usr/local/lib/python3.9/site-packages/sqlalchemy/sql/compiler.py", line 2534, in render_literal_bindparam
2024-01-28 12:03:39     to_update, replacement_expr = leep(bindparam, value)
2024-01-28 12:03:39   File "/usr/local/lib/python3.9/site-packages/sqlalchemy/sql/compiler.py", line 2091, in _literal_execute_expanding_parameter_literal_binds
2024-01-28 12:03:39     replacement_expression = ", ".join(
2024-01-28 12:03:39   File "/usr/local/lib/python3.9/site-packages/sqlalchemy/sql/compiler.py", line 2092, in <genexpr>
2024-01-28 12:03:39     self.render_literal_value(value, parameter.type)
2024-01-28 12:03:39   File "/usr/local/lib/python3.9/site-packages/virtuoso/alchemy.py", line 215, in render_literal_value
2024-01-28 12:03:39     if isinstance(value, IRI_ID_Literal):
2024-01-28 12:03:39 NameError: name 'IRI_ID_Literal' is not defined
2024-01-28 12:03:39 2024-01-28 12:03:39,327:ERROR:superset.views.base:name 'IRI_ID_Literal' is not defined
2024-01-28 12:03:39 Traceback (most recent call last):
2024-01-28 12:03:39   File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1823, in full_dispatch_request
2024-01-28 12:03:39     rv = self.dispatch_request()
2024-01-28 12:03:39   File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1799, in dispatch_request
2024-01-28 12:03:39     return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
2024-01-28 12:03:39   File "/usr/local/lib/python3.9/site-packages/flask_appbuilder/security/decorators.py", line 95, in wraps
2024-01-28 12:03:39     return f(self, *args, **kwargs)
2024-01-28 12:03:39   File "/app/superset/views/base_api.py", line 127, in wraps
2024-01-28 12:03:39     raise ex
2024-01-28 12:03:39   File "/app/superset/views/base_api.py", line 121, in wraps
2024-01-28 12:03:39     duration, response = time_function(f, self, *args, **kwargs)
2024-01-28 12:03:39   File "/app/superset/utils/core.py", line 1526, in time_function
2024-01-28 12:03:39     response = func(*args, **kwargs)
2024-01-28 12:03:39   File "/app/superset/utils/log.py", line 255, in wrapper
2024-01-28 12:03:39     value = f(*args, **kwargs)
2024-01-28 12:03:39   File "/app/superset/charts/data/api.py", line 256, in data
2024-01-28 12:03:39     return self._get_data_response(
2024-01-28 12:03:39   File "/app/superset/charts/data/api.py", line 415, in _get_data_response
2024-01-28 12:03:39     result = command.run(force_cached=force_cached)
2024-01-28 12:03:39   File "/app/superset/charts/data/commands/get_data_command.py", line 45, in run
2024-01-28 12:03:39     payload = self._query_context.get_payload(
2024-01-28 12:03:39   File "/app/superset/common/query_context.py", line 100, in get_payload
2024-01-28 12:03:39     return self._processor.get_payload(cache_query_context, force_cached)
2024-01-28 12:03:39   File "/app/superset/common/query_context_processor.py", line 590, in get_payload
2024-01-28 12:03:39     query_results = [
2024-01-28 12:03:39   File "/app/superset/common/query_context_processor.py", line 591, in <listcomp>
2024-01-28 12:03:39     get_query_results(
2024-01-28 12:03:39   File "/app/superset/common/query_actions.py", line 225, in get_query_results
2024-01-28 12:03:39     return result_func(query_context, query_obj, force_cached)
2024-01-28 12:03:39   File "/app/superset/common/query_actions.py", line 103, in _get_full
2024-01-28 12:03:39     payload = query_context.get_df_payload(query_obj, force_cached=force_cached)
2024-01-28 12:03:39   File "/app/superset/common/query_context.py", line 121, in get_df_payload
2024-01-28 12:03:39     return self._processor.get_df_payload(
2024-01-28 12:03:39   File "/app/superset/common/query_context_processor.py", line 159, in get_df_payload
2024-01-28 12:03:39     query_result = self.get_query_result(query_obj)
2024-01-28 12:03:39   File "/app/superset/common/query_context_processor.py", line 237, in get_query_result
2024-01-28 12:03:39     result = query_context.datasource.query(query_object.to_dict())
2024-01-28 12:03:39   File "/app/superset/connectors/sqla/models.py", line 1180, in query
2024-01-28 12:03:39     query_str_ext = self.get_query_str_extended(query_obj)
2024-01-28 12:03:39   File "/app/superset/connectors/sqla/models.py", line 843, in get_query_str_extended
2024-01-28 12:03:39     sql = self.database.compile_sqla_query(sqlaq.sqla_query)
2024-01-28 12:03:39   File "/app/superset/models/core.py", line 629, in compile_sqla_query
2024-01-28 12:03:39     sql = str(qry.compile(engine, compile_kwargs={"literal_binds": True}))
2024-01-28 12:03:39   File "/usr/local/lib/python3.9/site-packages/sqlalchemy/sql/elements.py", line 494, in compile
2024-01-28 12:03:39     return self._compiler(dialect, **kw)
2024-01-28 12:03:39   File "/usr/local/lib/python3.9/site-packages/sqlalchemy/sql/elements.py", line 558, in _compiler
2024-01-28 12:03:39     return dialect.statement_compiler(dialect, self, **kw)
2024-01-28 12:03:39   File "/usr/local/lib/python3.9/site-packages/sqlalchemy/sql/compiler.py", line 776, in __init__
2024-01-28 12:03:39     Compiled.__init__(self, dialect, statement, **kwargs)
2024-01-28 12:03:39   File "/usr/local/lib/python3.9/site-packages/sqlalchemy/sql/compiler.py", line 451, in __init__
2024-01-28 12:03:39     self.string = self.process(self.statement, **compile_kwargs)
2024-01-28 12:03:39   File "/usr/local/lib/python3.9/site-packages/sqlalchemy/sql/compiler.py", line 486, in process
2024-01-28 12:03:39     return obj._compiler_dispatch(self, **kwargs)
2024-01-28 12:03:39   File "/usr/local/lib/python3.9/site-packages/sqlalchemy/sql/visitors.py", line 82, in _compiler_dispatch
2024-01-28 12:03:39     return meth(self, **kw)
2024-01-28 12:03:39   File "/usr/local/lib/python3.9/site-packages/sqlalchemy/sql/compiler.py", line 3405, in visit_select
2024-01-28 12:03:39     text = self._compose_select_body(
2024-01-28 12:03:39   File "/usr/local/lib/python3.9/site-packages/sqlalchemy/sql/compiler.py", line 3563, in _compose_select_body
2024-01-28 12:03:39     t = self._generate_delimited_and_list(
2024-01-28 12:03:39   File "/usr/local/lib/python3.9/site-packages/sqlalchemy/sql/compiler.py", line 1702, in _generate_delimited_and_list
2024-01-28 12:03:39     return clauses[0]._compiler_dispatch(self, **kw)
2024-01-28 12:03:39   File "/usr/local/lib/python3.9/site-packages/sqlalchemy/sql/visitors.py", line 82, in _compiler_dispatch
2024-01-28 12:03:39     return meth(self, **kw)
2024-01-28 12:03:39   File "/usr/local/lib/python3.9/site-packages/virtuoso/alchemy.py", line 212, in visit_binary
2024-01-28 12:03:39     return super(VirtuosoSQLCompiler, self).visit_binary(binary, **kwargs)
2024-01-28 12:03:39   File "/usr/local/lib/python3.9/site-packages/sqlalchemy/sql/compiler.py", line 2192, in visit_binary
2024-01-28 12:03:39     return disp(binary, operator_, **kw)
2024-01-28 12:03:39   File "/usr/local/lib/python3.9/site-packages/virtuoso/alchemy.py", line 202, in visit_in_op_binary
2024-01-28 12:03:39     return self._generate_generic_binary(binary, " IN ", **kw)
2024-01-28 12:03:39   File "/usr/local/lib/python3.9/site-packages/sqlalchemy/sql/compiler.py", line 2258, in _generate_generic_binary
2024-01-28 12:03:39     + binary.right._compiler_dispatch(
2024-01-28 12:03:39   File "/usr/local/lib/python3.9/site-packages/sqlalchemy/sql/visitors.py", line 82, in _compiler_dispatch
2024-01-28 12:03:39     return meth(self, **kw)
2024-01-28 12:03:39   File "/usr/local/lib/python3.9/site-packages/sqlalchemy/sql/compiler.py", line 2438, in visit_bindparam
2024-01-28 12:03:39     ret = self.render_literal_bindparam(
2024-01-28 12:03:39   File "/usr/local/lib/python3.9/site-packages/sqlalchemy/sql/compiler.py", line 2534, in render_literal_bindparam
2024-01-28 12:03:39     to_update, replacement_expr = leep(bindparam, value)
2024-01-28 12:03:39   File "/usr/local/lib/python3.9/site-packages/sqlalchemy/sql/compiler.py", line 2091, in _literal_execute_expanding_parameter_literal_binds
2024-01-28 12:03:39     replacement_expression = ", ".join(
2024-01-28 12:03:39   File "/usr/local/lib/python3.9/site-packages/sqlalchemy/sql/compiler.py", line 2092, in <genexpr>
2024-01-28 12:03:39     self.render_literal_value(value, parameter.type)
2024-01-28 12:03:39   File "/usr/local/lib/python3.9/site-packages/virtuoso/alchemy.py", line 215, in render_literal_value
2024-01-28 12:03:39     if isinstance(value, IRI_ID_Literal):
2024-01-28 12:03:39 NameError: name 'IRI_ID_Literal' is not defined

**Comment by smalinin** [comment]
Did you try to execute SPARQL queries or what ?
This package is for SQL queries for now.

**Comment by E-Babkin** [comment]
Yes, pure SPARQL queries in Superset SQL lab work fairly well.
 SQL queries without any filters also work as expected.
 The problem happens only when Superset adds some additional parts to the query for effective filters.
  
  A scenario to reproduce is the following:
  1) Inside Superset GUI a SQL or SPARQL query is defined. Inside GUI (SQL Lab) that query correctly returns results
  3) inside GUI the query is used for specification of the Superset dataset and the widget, If the query is used alone, everything  is fine.
  4) inside GUI if a filter on the field is added to the Superset dataset, then the reported error is returned.
    It seems Superset adds something to the original query that can not be processed inside Virtuoso/Alchemy.

**Comment by smalinin** [comment]
Ok, I will try to check

**Comment by smalinin** [comment]
@E-Babkin 
Fixed.
You need install:
- latest version of Virtuoso-SQLAlchemy - it was fixed
- install Apache Superset from https://github.com/OpenLinkSoftware/superset/releases/download/4.0.1.virtuoso/apache-superset-4.0.1.virtuoso.tar.gz   (source https://github.com/OpenLinkSoftware/superset/tree/4.0.1.virtuoso )
   The updated package includes engine spec for Virtuoso.
You could install it via:
```
pip install https://github.com/OpenLinkSoftware/superset/releases/download/4.0.1.virtuoso/apache-superset-4.0.1.virtuoso.tar.gz
```

**Comment by E-Babkin** [comment]
@smalinin , thank you for resolving that issue.

I made an attempt to build the docker images of the updated package of Superset, however I have got the build error.
WARNING in ./src/utils/textUtils.ts 21:11-44
Module not found: Error: Can't resolve '../../../superset_text' in '/app/superset-frontend/src/utils'

Could you please describe the sequence of actions you did to test the modified version ?

**Comment by E-Babkin** [comment]
Thank you for quick fixing.
In the result Saved queries work well in Superset.

However the tables (DataSources) from Virtuoso can not be processed correctly.

If a table (or a view) is selected for the Superset Chart, the following error is displayed:

![image](https://github.com/OpenLinkSoftware/Virtuoso-SQLAlchemy/assets/9838609/7fa87a97-7cd5-4a1a-a9e0-bc130bdb42a2)


The trace from Superset log is 

2024-05-18 00:04:28,970:WARNING:superset.connectors.sqla.models:Query SELECT TOP 1000 "name" AS "name",
2024-05-18 01:04:28            owner AS owner
2024-05-18 01:04:28 FROM "DBA".."WINDFARM_ASSET_MAINTETNANCE_LOG"
2024-05-18 01:04:28 GROUP BY "name",
2024-05-18 01:04:28          owner on schema DBA failed
2024-05-18 01:04:28 Traceback (most recent call last):
2024-05-18 01:04:28   File "/app/superset/connectors/sqla/models.py", line 1793, in query
2024-05-18 01:04:28     df = self.database.get_df(sql, self.schema, mutator=assign_column_label)
2024-05-18 01:04:28   File "/app/superset/models/core.py", line 604, in get_df
2024-05-18 01:04:28     self.db_engine_spec.execute(cursor, sqls[-1])
2024-05-18 01:04:28   File "/app/superset/db_engine_specs/base.py", line 1592, in execute
2024-05-18 01:04:28     raise cls.get_dbapi_mapped_exception(ex) from ex
2024-05-18 01:04:28   File "/app/superset/db_engine_specs/base.py", line 1590, in execute
2024-05-18 01:04:28     cursor.execute(query)
2024-05-18 01:04:28 pyodbc.ProgrammingError: ('42S02', '[42S02] [OpenLink][Virtuoso ODBC Driver][Virtuoso Server]SQ200: No table DBA..WINDFARM_ASSET_MAINTETNANCE_LOG (-1) (SQLExecDirectW)')

Could you please fix that small issue.
