### ISSUE TITLE
Incorrect composition of Database, username and the table in the SQL query if a physical table is used as a dataset

### ISSUE THREAD

**Issue by E-Babkin** [OpenLinkSoftware/Virtuoso-SQLAlchemy#4]
If a table (or a view) is selected for the Dataset and then the Chart is updated, the following error is displayed:

![image](https://github.com/OpenLinkSoftware/Virtuoso-SQLAlchemy/assets/9838609/7fa87a97-7cd5-4a1a-a9e0-bc130bdb42a2)

The trace from Superset log is 

2024-05-18 00:04:28,970:WARNING:superset.connectors.sqla.models:Query SELECT TOP 1000 "name" AS "name",
2024-05-18 01:04:28            owner AS owner
2024-05-18 01:04:28 FROM "DBA".."WINDFARM_ASSET_MAINTETNANCE_LOG"
2024-05-18 01:04:28 GROUP BY "name",
2024-05-18 01:04:28          owner on schema DBA failed
2024-05-18 01:04:28 Traceback (most recent call last):
2024-05-18 01:04:28   File "/app/superset/connectors/sqla/models.py", line 1793, in query
2024-05-18 01:04:28     df = self.database.get_df(sql, self.schema, mutator=assign_column_label)
2024-05-18 01:04:28   File "/app/superset/models/core.py", line 604, in get_df
2024-05-18 01:04:28     self.db_engine_spec.execute(cursor, sqls[-1])
2024-05-18 01:04:28   File "/app/superset/db_engine_specs/base.py", line 1592, in execute
2024-05-18 01:04:28     raise cls.get_dbapi_mapped_exception(ex) from ex
2024-05-18 01:04:28   File "/app/superset/db_engine_specs/base.py", line 1590, in execute
2024-05-18 01:04:28     cursor.execute(query)
2024-05-18 01:04:28 pyodbc.ProgrammingError: ('42S02', '[42S02] [OpenLink][Virtuoso ODBC Driver][Virtuoso Server]SQ200: No table DBA..WINDFARM_ASSET_MAINTETNANCE_LOG (-1) (SQLExecDirectW)')

Could you please fix that small issue.

_Originally posted by @E-Babkin in https://github.com/OpenLinkSoftware/Virtuoso-SQLAlchemy/issues/2#issuecomment-2118512427_
           

The correct reference to the table should include the user name, like
"DB."DBA"."WINDFARM_ASSET_MAINTETNANCE_LOG"

**Comment by smalinin** [comment]
I will look on this and prepare fix

**Comment by smalinin** [comment]
Fixed, try with updated Virtuoso-SQLAlchemy dialect

**Comment by E-Babkin** [comment]
Thank you for the fix, it works now inside Superset like a magic :)
